#!/bin/sh
# Vortex announcements — generate the Basic-auth reader map.
#
# Writes /etc/nginx/conf.d/00-vortex-readers.conf, loaded at http context
# before the server block rendered from vortex-announcements.conf.template
# (conf.d is included alphabetically). Consumed by the
# `if ($vortex_feed_authorized = 0)` check in the feed location.
#
# VORTEX_FEED_READERS: whitespace-separated user:password pairs, e.g.
#   VORTEX_FEED_READERS="nuc1:s3cret nuc2:other"
# Empty/unset = public feed (no authentication required).
#
# Passwords must not contain whitespace (that's the pair separator).
#
# Why regex entries instead of plain string keys: nginx matches map STRING
# keys case-insensitively ("Strings are matched ignoring the case",
# ngx_http_map_module docs — verified empirically on nginx 1.27). A plain
# key "Basic <base64>" would therefore also accept every case-VARIANT of
# the base64 blob — and different case variants decode to DIFFERENT
# passwords (e.g. nuc1:secret1 vs nuc1:Yecret1), silently widening the
# accepted credential set. Anchored case-sensitive regexes ("~…") match
# the base64 blob exactly, while still tolerating RFC 7617 scheme-case
# ("basic"/"Basic") and multiple spaces between scheme and credentials.

set -eu

out=/etc/nginx/conf.d/00-vortex-readers.conf

{
    echo '# Generated by 25-vortex-readers.sh — do not edit by hand.'
    echo 'map $http_authorization $vortex_feed_authorized {'
    if [ -z "${VORTEX_FEED_READERS:-}" ]; then
        echo '    default 1; # no VORTEX_FEED_READERS configured: public feed'
    else
        echo '    default 0;'
        echo '    ""      0;'
        for reader in ${VORTEX_FEED_READERS}; do
            # busybox base64 wraps output; strip newlines to one map line
            cred=$(printf '%s' "$reader" | base64 | tr -d '\n')
            # PCRE-escape the two special characters base64 can contain
            esc=$(printf '%s' "$cred" | sed -e 's|+|\\+|g' -e 's|/|\\/|g')
            # printf, NOT echo: busybox echo would eat the \t and risk mangling
            # other backslashes in the escaped credentials. The literal \t
            # below is fine — nginx converts it to a tab inside quoted strings.
            printf '%s\n' "    \"~^[Bb][Aa][Ss][Ii][Cc][ \t]+${esc}\$\" 1;"
        done
    fi
    echo '}'
} > "$out"

echo "$0: wrote $out"
